### ISSUE TITLE
Add support for RR-MAIN-REP-WH for occupancy status

### ISSUE THREAD

**Issue by benjimatt** [upsert/lutron-caseta-pro#27]
So as much as I want to just purchase the RA2 select I'm starting to think that Lutron isn't going to add functionality for sensor status via telnet.  So I have decided to purchase the RR-MAIN-REP-WH RadioRA 2 main repeater and go this route.  I currently have the caseta pro so either way I'd have to get something different for motion.  

But I still want to be able to use HASS with the RR-MAIN-REP-WH to get picos and motion sensors.  I'm assuming it uses the same telnet protocol.   Would this be possible to implement.

**Comment by upsert** [comment]
There is a HASS component for RadioRa 2: https://www.home-assistant.io/components/lutron/. It has a significantly different XML format integration report and I think a few differences in features in the integration protocol (occupancy being one of them).

Looks like they have events for keypad button presses rather than a sensor. Not sure if occupancy sensors also generate events, but if they don't I'm sure someone could implement it. Even better for that component would be a [binary sensor](https://www.home-assistant.io/components/binary_sensor/) with device class `occupancy`. That is how I would do it if it ever comes to Ra2 Select.

Also good to keep in mind with RadioRa 2 is that apart from the Main Repeater you need the additional expense of a Lutron Connect bridge (~ $200) which has all the modern stuff like Homekit, Sonos, Alexa, Google Assistant etc.. Connect Bridge I think is also missing IFTTT, Apple Watch support, Harmony integration and some other consumer oriented stuff. You can compare the features on [here](http://www.lutron.com/en-US/Products/Pages/SingleRoomControls/CasetaWireless/Applications.aspx) versus [here](http://www.lutron.com/en-US/Products/Pages/WholeHomeSystems/RadioRA2/Integration.aspx).
