### ISSUE TITLE
Scenes with covers don't work after upgrading to 0.101.x

### ISSUE THREAD

**Issue by oleggold** [upsert/lutron-caseta-pro#38]
The syntax of scene has changed in 0.101.x and it is now required that every entity in a scene has the state declared.
Adding the state fixed scenes syntax errors, but scene does nothing when activated.
Below is from my configuration.yaml:
`
scene:
  - name: Office Almost Sheer
    entities:
      cover.office_blackout:
        state: open
        current_position: 80
      cover.office_sheer:
        state: closed
        current_position: 0
`
I tried using the position instead of current_position, but it did not help.

**Comment by upsert** [comment]
Looks like they broke the scene component. I will need to add some state attributes.

**Comment by upsert** [comment]
After further investigation, they are using state attributes that rely on `current_cover_position` which is already implemented, so no changes are needed.

I tested with a scene with `state` and `current_position` and it seems to work. Also looked at other cover implementations built into Home Assistant and did not see any changes to other components triggered by the breaking change in scene.

If you still cannot get it to work, it may be easier to create that scene externally in the Lutron app since it appears to be all Lutron devices.

**Comment by oleggold** [comment]
Would you mind posting the configuraiton.yaml definition of the scene with covers that you have tested with?
Thanks.
