### ISSUE TITLE
View dimmer switch as a switch and not a light?

### ISSUE THREAD

**Issue by silfa718** [upsert/lutron-caseta-pro#49]
I have a lutron dimmer switch and want to see when in HA when the off button is pressed to trigger an automation. But the dimmer only shows up in HA as a light. I feel this might not be possible because that is how the switch is represented in the app, more like a light than a switch.

**Comment by upsert** [comment]
You can trigger an automation on the state of the light. Trigger Type of 'State', entity is your light, and the To state would be 'off'.

You could also use a [Template Binary Sensor](https://www.home-assistant.io/integrations/binary_sensor.template/) if you want to break it out to an entity.

You could also [configure the device as a switch](https://github.com/upsert/lutron-caseta-pro/blob/master/ReadMe.md#configuration) in this component, however you would lose the ability to dim the light.

**Comment by silfa718** [comment]
Thanks, I will give your second suggestion a try.

**Comment by silfa718** [comment]
I got it show as a switch and not a light in HA, but it doesn't help with what I am try to do and maybe I didn't explain what I wanted clearly.

I was looking to see if I can tell that the dimmer Off button (or any button) was pressed irregardless of the state of the light/switch. 

For example, the light that the physical dimmer switch is connected to is off and HA shows the state of the light is off, I push the off button on the dimmer switch, HA sees that the Off button was pressed.

**Comment by upsert** [comment]
There are no events generated for dimmers or switches for what you are describing for button presses. There is only the level of the light that changes.

You can use a pico for that though and they are much more versatile. They are cheap and can be mounted beside an existing single gang box (PICO-WBX-ADAPT + CW-2-WH) and provide a button which you can clearly label. It would probably be easier to use rather than having to know the magic button presses on your dimmers. They come in 4-button, 2-button and 3-button with raise/lower.

**Comment by silfa718** [comment]
@upsert Thanks for the detailed answer.

 I have about 5 picos deployed around the house. If I do go the pico route I would have to hard wire the current light and I would rather not have to do that or mount a third pico next to the switches, but looks like that might be my only options.
