### ISSUE TITLE
Controlling lamp dimmer as two separate switches/lights

### ISSUE THREAD

**Issue by snowe2010** [upsert/lutron-caseta-pro#59]
I can't tell if it's possible from the documentation, but is it possible or will it ever be possible to control the two sides of a plug-in dimmer as two separate switches/lights?

**Comment by steleary** [comment]
I do t think that is possible since you can not even do it in the native app.   I believe the whole module is one dimmer.

On May 26, 2020, at 4:03 PM, Tyler Thrailkill <notifications@github.com> wrote:

﻿

I can't tell if it's possible from the documentation, but is it possible or will it ever be possible to control the two sides of a plug-in dimmer as two separate switches/lights?

**Comment by snowe2010** [comment]
Dang, that's what I thought. I just hoped that lutron wasn't providing the functionality, but that it was actually there. :(
