### ISSUE TITLE
support for `RR-SEL-REP2-BL`?

### ISSUE THREAD

**Issue by JonGilmore** [upsert/lutron-caseta-pro#65]
sorry, im struggling to find information on this anywhere, but is the `RR-SEL-REP2-BL` the same as the `RR-SEL-REP2S`? I can't find much information on the `RR-SEL-REP2S` repeater, but I realize that is what is listed on the main readme. 
Thanks!

**Comment by upsert** [comment]
The 'S' variants are distributed by Snap AV and have OvrC, their remote systems management software enabled. I would guess the hardware and firmware are identical, but because they have a different part number and device class identifier in the firmware, Snap AV can restrict which units can connect to their systems and possibly charge a different price and/or handle distribution.

You can tell from this page that it still uses the Telnet protocol required by this custom component:
https://www.snapav.com/shop/en/snapav/ovrc-enabled-lutron-reg%3B-ra2-select-main-repeater-lut-rr-sel-rep25

**Comment by JonGilmore** [comment]
Alright, that makes sense. So is it safe to say that this component supports `RR-SEL-REP2-BL` as well then?

**Comment by upsert** [comment]
Yes indeed.
