### ISSUE TITLE
Getting failed to call service error when trying to configure component. 

### ISSUE THREAD

**Issue by ghurty** [upsert/lutron-caseta-pro#71]
I am trying to configure the component. When I paste my integration report I get the following error:
failed to call service configurator/configure expected value line 1 column 1 (char 0).

Any suggestions?

Thank you

**Comment by upsert** [comment]
Possible copy/paste issue?

I have gone back and reconfigured the component on the latest Home Assistant 2020.12.1 and confirmed it is still working as expected with the configurator.

**Comment by tjfoth** [comment]
I am getting the same problem with the same release that you tested with.

**Comment by tjfoth** [comment]
I just found the problem: At least in the case of the IOS Lutron app, it indents the JSON file with causes errors with Python's JSON parser.  If you remove the leading spaces, it parses fine.

**Comment by cajuncoding** [comment]
Are you sending it to yourself via email and copying it after you receive the email, or are you copying it from the App UI?

I've not updated recently but I've never had any issues using the real email I receive.

**Comment by tjfoth** [comment]
Because I don't use IOS Mail, I let it compose the mail, copied the
integration report out of the composed email before it was sent, pasted it
into Gmail, and sent it.  I received it in the browser version of Gmail
(Google Chrome on MacOSX) and tried pasting it into the prompt.

---
Tom Foth
tom@fothmail.com
tom@foth.me

**Comment by cajuncoding** [comment]
In case it's helpful, I do no use Apple (iOS) mail either, only Gmail but it is configured on my iPhone. So the Lutron app uses the default mail provider it seems because the sent mail from the Lutron app appears in my sent folder of Gmail, and in my inbox because I sent it to myself.

Try copy/pasting into Notepad (if you use Windows) or Notepad++ which can help show any invalid characters...another option might be to run it through an online JSON formatter first to sanitize it...

**Comment by tjfoth** [comment]
I used Atom to remove the leading spaces and I'm good.

And my bad for not saying thank you for writing this code and making it
available.  It is awesome.

Tom

---
Tom Foth
tom@fothmail.com
tom@foth.me

**Comment by upsert** [comment]
Are the leading spaces before the first opening bracket of the JSON or are they inside individual values? A trim command could be added that would remove leading and trailing whitespace from the content entered in the configurator dialog.

**Comment by tjfoth** [comment]
It was before the brackets inside of the main bracket.

Much like python indenting.

---
Tom Foth
tom@fothmail.com
tom@foth.me
