### ISSUE TITLE
Integration 'lutron_caseta_pro' not found.

### ISSUE THREAD

**Issue by wisscot** [upsert/lutron-caseta-pro#81]
Hi, 
Does this repo still work?  The latest update seems one year ago at Feb 2022.  

I am trying to use this custom component since the Home Assistant build-in integration (which uses LEAP?) seems not support/cannot be triggered by wired in wall switch/dimmer button (NOT pico).  

I am new to HA and I just followed the `First Time Setup` steps 1-3 and tried to restart HA.  Then I got this error
```
The system cannot restart because the configuration is not valid: Integration error: lutron_caseta_pro - Integration 'lutron_caseta_pro' not found.
```
Here's my file structure
```
├── configuration.yaml
├── custom_components
│   └── lutron_caseta_pro
│       ├── casetify.py
│       ├── cover.py
│       ├── fan.py
│       ├── __init__.py
│       ├── light.py
│       ├── manifest.json
│       ├── scene.py
│       ├── sensor.py
│       └── switch.py
```
And added following to configuration.yaml
```
lutron_caseta_pro:
    bridges:
      - host: 192.168.1.10
        mac: 48:5e:aa:bb:cc
```
Env: Home Assistant 2022.12.1  in docker in ubuntu 20.04. 

p.s. It has "version" key in `custom_components/lutron_caseta_pro/manifest.json` so this probably not the issue. 

Any help or pointers are appreciated!

**Comment by cajuncoding** [comment]
It’s working fine for me…strongly recommend using HACS to install it.

**Comment by upsert** [comment]
It does indeed still work and your file structure looks okay.

With that being said, this custom component uses the telnet protocol and it does not generate any events for buttons presses on dimmers or switches. The only thing you will see is the change in the light level.

This question often comes up when people are trying to add secondary functions or special tap sequences to existing dimmers or switches. In the Lutron world, you would do this by adding a pico remote. They are inexpensive, require no extra wiring and mount directly to wall with an adapter kit (PICO-WBX-ADAPT). It only requires replacing your light switch face plate with an extra gang and you will never know there is no box behind it.

The pico remotes, particularly the 4 button (e.g. PJ2-4B-GWH-L31) and 2 button scene remotes, offer a better user experience and a world of possibilities when integrated with Home Assistant. You program the lighting scenes through the Lutron app and then use automations in Home Assistant to integrate garage doors, Zigbee bulbs, HVAC etc. and can go far beyond even the high end Lutron HomeWorks QS, which is orders of magnitude more extensive than Caseta. It may take some adjustment to start thinking of lighting in terms of scenes instead of devices, but it is well worth the effort. You can also label the pico remotes with a label maker with transparent-backed labels and it will be easy to understand for all users.

**Comment by wisscot** [comment]
Thank you @cajuncoding for confirming and @upsert for the detailed explanation and suggestions!  Yea, I just realized that , even this repo cannot generate event for wired switch button press, by reading from other solved issues in this repo.  

I think I will stick with pico or use a scene pad then.  Thanks again and closing this issue.
